### PR TITLE
Remove double spaces before `from`

### PR DESCRIPTION
**Pull request by VincentMolinie**

### CODE REVIEW

**Comment by VincentMolinie** [comment]
@averydev , could you please merge this :)

**Comment by VincentMolinie** [comment]
@jackson-dean could you please merge this :)?

**Comment by jackson-dean** [comment]
@VincentMolinie I don't have write access on this repo. I simply fixed some previous spacing issues. However, I have noticed that a new version of the vscode plugin has still not been published since that fix which is pretty annoying. It may be that this is a dead repo... I have no idea. @averydev I would be willing to take it over but I would also need to be able to publish the vscode plugin as well.

**Comment by VincentMolinie** [comment]
Thanks for your reply ^^. I hope not :/ may be we can just fork it and
create a new one

--
Molinié Vincent
Full-Stack Developer at ForestAdmin

Le mer. 15 mai 2019 à 16:29, Jackson Dean <notifications@github.com> a
écrit :

**Comment by VincentMolinie** [comment]
One more trye, @averydev and @jackson-dean  please can you merge this 🙏

**Comment by jackson-dean** [comment]
@VincentMolinie I think we’ll have to fork. There are actually more things we could add too now that decorators are in ember-source. Maybe other things too. I don’t think this repo is being maintained.

**Comment by averydev** [comment]
Hi there guys... Sorry for the delay I missed the notifications!

I’ll get this merged and deployed today.

I’m all ears if there are other adjustments you’d like to see!

**Pull request merged**
