### PR TITLE
Invoke snippets with `em.` instead of `E.`

### PR DESCRIPTION
**Pull request by davelowensohn**
As per #3

### CODE REVIEW

**Comment by averydev** [comment]
You'll have to do a find + replace of `E.` in this here file:
https://github.com/candidmetrics/ember-module-snippets/blob/master/snippets/snippets.json

The converter file is just the code that can do the transform from scratch, but it isn't actually invoked in the extension. The output is the snippets file, which is just one long file in the end...

**Comment by davelowensohn** [comment]
Yep, that's in there - probably just not previewing because there's 170+ changes.

**Comment by averydev** [comment]
Ah, gotcha, yeah missed that :)

Is there a way to alert users that there has been a change in an extension? I've been looking around but haven't come up with anything.

**Comment by davelowensohn** [comment]
Hmm. I'm not seeing anything either. Have you checked your VS Marketplace publisher area?

**Pull request closed without merging**
